### ISSUE TITLE
[QUESTION] 404 Not Found 

### ISSUE THREAD

**Issue by lake2** [npm/libnpmpublish#20]
# What / Why

my code：
```
const lib = require('libnpmpublish');
const pack = require('libnpmpack');
const path = require('path');

const resolve = (...str) => path.resolve(__dirname, ...str);

const pkg = require(resolve('./dist/package.json'));

async function run() {
    const tarball = await pack(resolve('./dist/'));

    await lib.publish(pkg, tarball, {
        access: true,
        token: 'XXX',
    });
}

run();
```

result:
```
(node:22460) UnhandledPromiseRejectionWarning: HttpErrorGeneral: 404 Not Found - PUT https://registry.npmjs.org/@sqlflow%2ftest - Not found
    at D:\VS Code\sqlflow_frontend\package\node_modules\npm-registry-fetch\check-response.js:134:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.publish (D:\VS Code\sqlflow_frontend\package\node_modules\libnpmpublish\publish.js:43:12)
    at async run (D:\VS Code\sqlflow_frontend\package\publish\index.js:12:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Where

* npm package @sqlflow/test
* https://registry.npmjs.org/@sqlflow%2ftest

**Comment by marcelovicentegc** [comment]
Hi, @lake2! Did you happen to figure out what happened? I'm facing the same response. I generated an Automation token for this since it doesn't require 2FA - which I have enabled - but I still get a 404 with the same options as you.

```ts
    const manifest = await pacote.manifest(APP_PATH);
    const tarData = await pacote.tarball(APP_PATH);

    manifest.version = patch(manifest.version);

    try {
      await publish(manifest, tarData, {
        access: true,
        token: process.env.TOKEN,
      });
    } catch (error) {
      Sentry.captureException(error);
      throw error;
    }
```

**Comment by ggrossetie** [comment]
@marcelovicentegc I had the same issue and found a solution while reading `npm-registry-fetch`: https://github.com/npm/npm-registry-fetch/blob/9cd725786b1362df268afda7b6e2a6c3db8ab05e/auth.js#L52-L60

In my case `regKey` is `undefined` so instead of using `{ token: process.env.TOKEN }`, I'm now using:

```js
{
  forceAuth: {
    token: process.env.TOKEN
  }
}
```

Your code should read:

```js
await publish(manifest, tarData, {
  access: true,
  forceAuth: {
    token: process.env.TOKEN
  }
});
```
